### ISSUE TITLE
[Bug]: Compile issue

### ISSUE THREAD

**Issue by Bortus-AI** [TheSonicMaster/MassOS#48]
### Checklist

- [X] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported.
- [X] If this is an issue with a specific program, I have checked the upstream project's issue tracker and determined that it is an issue with MassOS itself.

### MassOS version

N/A

### Subject

- [ ] Issue at runtime of MassOS.
- [ ] Issue with the MassOS Live CD.
- [ ] Issue with installing MassOS.
- [ ] Issue with the MassOS documentation.
- [X] Issue compiling MassOS from source.

### Expected Behavior

to complete

### Actual Behavior

When I run sudo ./stage2.sh I get the following 

james@massos:~/MassOS$ sudo ./stage2.sh
[sudo] password for james:     
Entering chroot environment in /home/james/MassOS/massos-rootfs...
Generating locale en_US.UTF-8... done
Locales successfully generated.
tar: rust-1.64.0-x86_64-unknown-linux-gnu.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Exiting chroot environment...
Chroot exited with unsuccessful exit code 2.

I have tried 3 times and can't get past this. Any guidance would be appreciated.

Thanks

**Comment by DanielMYT** [comment]
Thanks for reporting this. It should be fixed in the most recent commit to development (you may need to use `git pull` to update your local checkout, or delete and re-clone your local sources directly). Please note that you should also restart the build by running something like `sudo rm -rf massos-rootfs` and then re-running retrieve-sources, stage1, etc.

Please note that as you are building from the development branch, there is likely to be subsequent issues. The development branch is used for experimental changes which in many cases could cause API breakages or introduce something before it becomes properly documented. Therefore, if you are a first time builder, it is recommended to build the stable version until you are familiar with how the build system works.

**Comment by Bortus-AI** [comment]
Thank you that bug seems to be fixed now. I also noticed that the url for zlib 1.2.12 is broken. Can I change this to zlib 1.2.13 or should I use a different url to grab 1.2.12?

Thanks

**Comment by DanielMYT** [comment]
Another commit has now been pushed which has many package updates including zlib 1.2.13 which is now using a GitHub link so should no longer have expiration issues.

**Comment by Bortus-AI** [comment]
> Another commit has now been pushed which has many package updates including zlib 1.2.13 which is now using a GitHub link so should no longer have expiration issues.

Awesome thank you!
